services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - target: ${APP_PORT:-5000}
        published: ${APP_PORT:-5000}
        protocol: tcp
        mode: host
    networks:
      - leolink-network
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./docker/postgres
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - target: 5432
        published: ${DB_PORT:-5432}
        protocol: tcp
        mode: host
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - leolink-network

networks:
  leolink-network:
    driver: bridge
